export const PROFILE_REGISTER_REQUEST = 'PROFILE_REGISTER_REQUEST';
export const PROFILE_REGISTER_SUCCESS = 'PROFILE_REGISTER_SUCCESS';
export const PROFILE_REGISTER_FAIL = 'PROFILE_REGISTER_FAIL';

export const PROFILE_LOGIN_REQUEST = 'PROFILE_LOGIN_REQUEST';
export const PROFILE_LOGIN_SUCCESS = 'PROFILE_LOGIN_SUCCESS';
export const PROFILE_LOGIN_FAIL = 'PROFILE_LOGIN_FAIL';
